name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        run: rustup update stable && rustup target add wasm32-unknown-unknown

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Trunk via binstall
        run: cargo binstall trunk -y

      - name: Generate data
        run: cargo run -p evaluator -- 6 ./web/assets/shards

      - name: Build with Trunk
        run: trunk build --release --public-url /mahjong-sim/
        working-directory: ./web

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./web/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
