[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
gloo-net = "0.7.0"
wasm-bindgen-futures = "0.4.71"
yew = { version = "0.23.0", features = ["csr"] }
rkyv = { workspace = true }
util = { path = "../util" }
wasm-bindgen = "0.2.121"
# web-sys = "0.3.98"

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "console"
]